<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <PackageId>SNRHos</PackageId>
    <Version>2.0.6</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>fabiohcnobre</Authors>
		<Company>fabiohcnobre</Company> 
    <Description>Biblioteca para integração com o Sistema Nacional de Registro de Hóspedes (SNRHos), solução digital desenvolvida pelo Ministério do Turismo em parceria com o Serpro, que substitui a Ficha Nacional de Registro de Hóspedes (FNRH). Este pacote auxilia no envio de informações de pré check-in, check-in e check-out, atendendo às exigências da Lei nº 11.771/2008 e do Decreto nº 7.381/2010, facilitando a transmissão eletrônica de dados de hóspedes.</Description>
		<PackageDescription>Biblioteca para integração com o Sistema Nacional de Registro de Hóspedes (SNRHos), solução digital desenvolvida pelo Ministério do Turismo em parceria com o Serpro, que substitui a Ficha Nacional de Registro de Hóspedes (FNRH). Este pacote auxilia no envio de informações de pré check-in, check-in e check-out, atendendo às exigências da Lei nº 11.771/2008 e do Decreto nº 7.381/2010, facilitando a transmissão eletrônica de dados de hóspedes.</PackageDescription>
		<Copyright>Licença Apache-2.0</Copyright> 
		<RepositoryUrl>https://github.com/fabiohcnobre/SNRHos.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>https://github.com/fabiohcnobre/SNRHos</PackageProjectUrl>
		<PackageIcon>images.jpg</PackageIcon>
		<RepositoryUrl>https://github.com/fabiohcnobre/SNRHos.git</RepositoryUrl>
		<PackageTags>SNRHos, fnrh, turismo, Brasil, Serpro, FNRH Digital</PackageTags>
		<PackageReleaseNotes>Ajustes gerais foram realizados; a versão antiga será descontinuada em breve — mais detalhes no GitHub. Mais ajuste de Github.</PackageReleaseNotes>
		<NeutralLanguage>pt-BR</NeutralLanguage>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\images.jpg">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
		<None Include="LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
