name: Publish NuGet 

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release

      - name: Pack
        run: dotnet pack -c Release -o out

      - name: Publish
        run: dotnet nuget push "out/*.nupkg" --api-key ${{ secrets.YOUR_GITHUB_PAT }} --source "github"
